### ISSUE TITLE
Game crashes when trying to break 1.21

### ISSUE THREAD

**Issue by 0Eshan7** [bunnyi116/fabric-bedrock-miner#29]
Time: 2024-06-21 23:42:23
Description: Unexpected error

java.lang.NoSuchFieldError: Class net.minecraft.class_1893 does not have member field 'net.minecraft.class_1887 field_9131'
	at yan.lx.bedrockminer.utils.InventoryManagerUtils.getBlockBreakingSpeed(InventoryManagerUtils.java:159)
	at yan.lx.bedrockminer.utils.InventoryManagerUtils.isInstantBreakingBlock(InventoryManagerUtils.java:127)
	at yan.lx.bedrockminer.utils.InventoryManagerUtils.canInstantlyMinePiston(InventoryManagerUtils.java:110)
	at yan.lx.bedrockminer.task.TaskManager.reverseCheckInventoryItemConditionsAllow(TaskManager.java:165)
	at yan.lx.bedrockminer.task.TaskManager.addTask(TaskManager.java:51)
	at net.minecraft.class_310.handler$zzj000$bedrockminer$handleBlockBreaking(class_310.java:4201)
	at net.minecraft.class_310.method_1590(class_310.java:1741)
	at net.minecraft.class_310.method_1508(class_310.java:2122)
	at net.minecraft.class_310.method_1574(class_310.java:1938)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at yan.lx.bedrockminer.utils.InventoryManagerUtils.getBlockBreakingSpeed(InventoryManagerUtils.java:159)
	at yan.lx.bedrockminer.utils.InventoryManagerUtils.isInstantBreakingBlock(InventoryManagerUtils.java:127)
	at yan.lx.bedrockminer.utils.InventoryManagerUtils.canInstantlyMinePiston(InventoryManagerUtils.java:110)
	at yan.lx.bedrockminer.task.TaskManager.reverseCheckInventoryItemConditionsAllow(TaskManager.java:165)
	at yan.lx.bedrockminer.task.TaskManager.addTask(TaskManager.java:51)
	at net.minecraft.class_310.handler$zzj000$bedrockminer$handleBlockBreaking(class_310.java:4201)
	at net.minecraft.class_310.method_1590(class_310.java:1741)
	at net.minecraft.class_310.method_1508(class_310.java:2122)

-- Uptime --
Details:
	JVM uptime: 341.065s
	Wall uptime: 321.423s
	High-res time: 313.741s
	Client ticks: 5898 ticks / 294.900s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['killua'/49, l='ClientLevel', x=-29.40, y=128.00, z=10.57]]
	Chunk stats: 256, 45
	Level dimension: minecraft:the_nether
	Level spawn location: World: (-16,75,16), Section: (at 0,11,0 in -1,4,1; chunk contains blocks -16,0,16 to -1,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4383 game time, 4383 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 37

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, appleskin, axolotlitemfix, bedrockminer, caffeineconfig, chesttracker, cloth-config, continuity, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, gammautils, indium, inventoryprofilesnext, iris, itemscroller, jackfredlib, jackfredlib-base, jackfredlib-colour, jackfredlib-extracommandsourcedata, jackfredlib-gps, jackfredlib-lying, jackfredlib-toasts, jade, libipn, litematica, logical_zoom, malilib, minihud, modmenu, no_fog, quartzelv, reeses-sodium-options, skinlayers3d, sodium, sodium-extra, tweakeroo, whereisit, xaerominimap, xaeroworldmap, yet_another_config_lib_v3, file/VanillaTweaks_r315231.zip, continuity:default, continuity:glass_pane_culling_fix

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 875893248 bytes (835 MiB) / 1409286144 bytes (1344 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3400G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) RX Vega 11 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 2048.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21912.14
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 16440.37
	Virtual memory used (MiB): 9961.20
	Swap memory total (MiB): 2176.00
	Swap memory used (MiB): 239.43
	Space in storage for jna.tmpdir (MiB): available: 144577.63, total: 242405.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 144577.63, total: 242405.00
	Space in storage for io.netty.native.workdir (MiB): available: 144577.63, total: 242405.00
	Space in storage for java.io.tmpdir (MiB): available: 144577.63, total: 242405.00
	Space in storage for workdir (MiB): available: 144577.63, total: 242405.00
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx12288m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		appleskin: AppleSkin 3.0.2+mc1.21
		axolotlitemfix: Axolotl Item Fix 1.1.9
		bedrockminer: Bedrock Miner 1.20.6-1.2.21
		chesttracker: Chest Tracker 2.4.7+1.21
			whereisit: Where Is It 2.5.0+1.21
				jackfredlib: JackFredLib 0.10.0+1.21
					jackfredlib-base: JackFredLib: Base 1.4.0+1.21
					jackfredlib-colour: JackFredLib: Colour 1.1.0+1.21
					jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.1.1+1.21
					jackfredlib-gps: JackFredLib: GPS 1.0.7+1.21
					jackfredlib-lying: JackFredLib: Lying 0.5.5+1.21
					jackfredlib-toasts: JackFredLib: Toasts 1.1.0+1.21
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.62
		continuity: Continuity 3.0.0-beta.5+1.21
		fabric-api: Fabric API 0.100.1+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.65+b559734490
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b9990
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a790
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a790
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa1990
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.11+b559734490
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.12+7f945d5b90
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.2.1+d153f34490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a790
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.22+6a6dfa1990
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.6+16c4ae2590
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9990
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b9990
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8c90
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92190
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.0+00ab0a6390
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.9+98a7dbbb90
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.9+6573ed8c90
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c90
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b90
			fabric-networking-api-v1: Fabric Networking API (v1) 4.1.0+686dcdce90
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.10+d132107690
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c90
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.8+6573ed8c90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.21+b9828ba390
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.16+fe474d6b90
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.3+cc9f121a90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.66+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b559734490
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.69+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.3+d132107690
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f34490
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.3+b559734490
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.78+b559734490
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.12+b559734490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8c90
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		gammautils: Gamma Utils 1.9.20
		indium: Indium 1.0.33+mc1.21
		inventoryprofilesnext: Inventory Profiles Next 2.0.0
		iris: Iris 1.7.1+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemscroller: Item Scroller 0.23.999-sakura.1
		jade: Jade 15.0.4+fabric
		java: OpenJDK 64-Bit Server VM 21
		libipn: libIPN 5.0.0
		litematica: Litematica 0.18.999-sakura.4
		logical_zoom: Logical Zoom 0.0.25
		malilib: MaLiLib 0.19.999-sakura.2
		minecraft: Minecraft 1.21
		minihud: MiniHUD 0.31.999-sakura.3
		modmenu: Mod Menu 11.0.0-beta.1
		mousetweaks: Mouse Tweaks 2.26
		no_fog: No Fog 1.3.6+1.16.5-1.21
		quartzelv: Quartz Elevator 2.3.0+1.21
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.21
		skinlayers3d: 3d-Skin-Layers 1.6.6
		sodium: Sodium 0.5.9+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		tweakeroo: Tweakeroo 0.20.999-sakura.2
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.38.8
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.15.11-1.21
	Launcher name: java-minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon(TM) RX Vega 11 Graphics GL version 3.2.0 Core Profile Context 24.3.1.240216, ATI Technologies Inc.
	Window size: 1366x768
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Render Distance: 2/2 chunks
	Resource Packs: vanilla, fabric, appleskin (incompatible), axolotlitemfix, bedrockminer, caffeineconfig, chesttracker, cloth-config, continuity, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, gammautils, indium, inventoryprofilesnext, iris, itemscroller, jackfredlib, jackfredlib-base, jackfredlib-colour, jackfredlib-extracommandsourcedata, jackfredlib-gps, jackfredlib-lying, jackfredlib-toasts, jade (incompatible), libipn, litematica, logical_zoom, malilib, minihud, modmenu, no_fog, quartzelv, reeses-sodium-options, skinlayers3d, sodium, sodium-extra, tweakeroo (incompatible), whereisit, xaerominimap (incompatible), xaeroworldmap (incompatible), yet_another_config_lib_v3 (incompatible), file/VanillaTweaks_r315231.zip, continuity:default, continuity:glass_pane_culling_fix
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 8x AMD Ryzen 5 3400G with Radeon Vega Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['killua'/49, l='ServerLevel[New World]', x=-29.40, y=128.00, z=10.57]]
	Active Data Packs: vanilla, fabric, collective, fabric-convention-tags-v2, quartzelv
	Available Data Packs: bundle, collective, fabric, fabric-convention-tags-v2, quartzelv, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 4449483545289723264

**Comment by bunnyi116** [comment]
1.21 I don't know much about it, because I updated it based on version 1.21.1。I'm working now. I'll deal with 1.21 when I have time.

**Comment by bunnyi116** [comment]
![image](https://github.com/bunnyi116/fabric-bedrock-miner/assets/37466008/4c0de048-7d56-498e-9263-e90b8bed0b7d)

I noticed you are using version 1.20.6 of fabric-bedrock-miner. If you are playing Minecraft version 1.21 or higher, you should use the new version.

**Comment by bunnyi116** [comment]
> 1.21 I don't know much about it, because I updated it based on version 1.21.1。I'm working now. I'll deal with 1.21 when I have time.



It seems I made a mistake; I was developing based on version 1.21 and didn't notice. Your issue is caused by using an old version of fabric-bedrock-miner, which leads to compatibility issues.

**Comment by 0Eshan7** [comment]
can you solve this issue

**Comment by bunnyi116** [comment]
https://github.com/bunnyi116/fabric-bedrock-miner/releases/download/Latest/bedrock-miner-1.21-1.2.21.jar
