### ISSUE TITLE
Didn't work in low TPS server

### ISSUE THREAD

**Issue by Yan-chanT** [bunnyi116/fabric-bedrock-miner#33]
When using this mod on a server with low TPS (ticks per second, normally 20), like the server I tried on with 8tps, the last "break and place another piston in very short time" action cannot place the second piston. It might because the action sequence is too fast for a slowed down server. 
I first tried manually placing down the second piston in offhand with a fast clicker at that time, it works sometimes with some timing and luck.
Then I used some method to slow down the speed of my client to match that of the server, the mod started to work! As long as my client speed matched the server tps, the mod never failed, except for a few retries that might caused by temporary tps wobbles.
However, slowing down the whole client makes the former sequence kinda slow, so it's the best if the mod can only adjust the last "break and place" interval to match the current server tps, either getting by automatic detection or by manual input with commands. 
Or it can might also be fixed by changing the last action from placing one piston into trying to place many pistons across a period of time.

**Comment by Yan-chanT** [comment]
More information(if needed):
Client version: 1.21
Server version: 1.21 Paper
Mod version: bedrock-miner-1.21-1.2.21
The Paper has all settable vanilla properties on, since it's a redstone server. No other noticeable plugins.

**Comment by bunnyi116** [comment]
Trying to fix it

**Comment by bunnyi116** [comment]
No follow-up replies for a long time, closing the issues.
