### ISSUE TITLE
为什么1.21破基岩速度特别慢

### ISSUE THREAD

**Issue by oneIdler** [bunnyi116/fabric-bedrock-miner#35]
无法多个基岩同时破，只能等上个破完之后才能破下一个

**Comment by bunnyi116** [comment]
这是因为我发现在1.21切换工具的时候破坏物品并不会使用当前发送的切换工具的数据包，会导活塞没办法秒破从而导致失败，具体原因不详，所以我为了能正常使用，将在执行前，发送切换工具的数据包，然后等待了几个TICK后(确保切换工具生效)才执行，为了保证切换工具的时候不被其他任务切换工具的影响，我将任务设置成一个TICK执行一个任务
