### ISSUE TITLE
不好意思，我有一些问题

### ISSUE THREAD

**Issue by WaterSwigger** [bunnyi116/fabric-bedrock-miner#37]
您好，中文不是我第一的语言，所以我的中文不太好。不好意思。

有时候我吧基岩挖掉的时候，还有一个活塞剩下来。有没有办法能吧这个活塞自己破坏掉吗？
还有，我感觉到挖基岩的时候有一点慢：我第一个基岩挖掉以后还有等一些时间才会开始挖第二个基岩。

谢谢！
非常感谢你做的mod。

**Comment by bunnyi116** [comment]
这是因为新版本代码的改动，导致无法秒切换使用工具进行破坏，所以我是在之前的前一TICK中去切换工具再执行,因为这个所以我限制为一个TICK执行一个任务。

目前我已经发现问题所在，但由于我没有空余时间进行处理

**Comment by bunnyi116** [comment]
```

 if (bl && blockState.calcBlockBreakingDelta(this.client.player, this.client.player.getWorld(), pos) >= 1.0F) {
                        this.breakBlock(pos);
                    }
```

```
    protected float calcBlockBreakingDelta(BlockState state, PlayerEntity player, BlockView world, BlockPos pos) {
        float f = state.getHardness(world, pos);
        if (f == -1.0F) {
            return 0.0F;
        } else {
            int i = player.canHarvest(state) ? 30 : 100;
            return player.getBlockBreakingSpeed(state) / f / (float)i;
        }
    }
```

目前我定位到是这个calcBlockBreakingDelta中的player.getBlockBreakingSpeed(state)获取的有问题

**Comment by bunnyi116** [comment]
getBlockBreakingSpeed目前这个问题无法修复，我在客户端模拟这些方法去测试，发现并不能解决这个问题，因为服务端代码也是调用该代码，所以这个问题短时间无法处理。

我只能尽可能优化操作流程让MOD能继续的正常工作下去。

此外，我已经发现另一种拉杆式的方法，有机会的我会尝试。

**Comment by bunnyi116** [comment]
无后续回复，关闭Issue
