### ISSUE TITLE
移除内置过滤器

### ISSUE THREAD

**Issue by glutinouscloud** [bunnyi116/fabric-bedrock-miner#41]
如题，工具本身不应对使用者的行为做出限制，但也不应为使用者的行为负责

**Comment by bunnyi116** [comment]
设计内置过滤器的原因是避免恶意使用模组去破坏服务器命令方块之类的方块，该举动会影响到服务端的安全性（包括开启状态时误点击方块）。

注：内置过滤器只针对与服务器生效，单人没有这个限制！

**Comment by bunnyi116** [comment]
如果你有这个需求，请自行修改源代码或手动通过常规方法破除
