### ISSUE TITLE
Area Clear?

### ISSUE THREAD

**Issue by F0xiikk** [bunnyi116/fabric-bedrock-miner#43]
Hi, would it be possible to make some modification to make it so that I would mark **pos1** and **pos2** for example 3x3x5 (length/width/height) and when I have it selected I would turn it on and **it would automatically start mining until it has all mined**? I personally tried to do something but failed. I am loser :DD

**Comment by bunnyi116** [comment]
I once tried to create a branch for development testing, but now I don't have much time to maintain this project (busy with work). I'm sorry~!

**Comment by F0xiikk** [comment]
All right, I get it. Actually, I was thinking about some kind of baritone or something, but it never worked. Theoretically you could do it through a macro record or something like that but if you ever have time for that that would be great. Just see if you have any notes, codes you could send? If not, that's totally fine. I was just wondering how you were doing. But I understand the time constraints, but otherwise, good job. Thank you for your quick response. 👍

**Comment by bunnyi116** [comment]
https://github.com/bunnyi116/fabric-bedrock-miner/blob/8a807a45226d01dbbccc669bd59b95e578a2a988/src/main/java/yan/lx/bedrockminer/task/TaskManager.java#L97-L124

This is my previous attempt.




https://github.com/bunnyi116/fabric-bedrock-miner/tree/dev-selection

**Comment by bunnyi116** [comment]
This was just my attempt at the time and may not work correctly, but I hope it can give you some ideas.

**Comment by F0xiikk** [comment]
Thank you, i will try.
